# Generated by Django 5.2.15 on 2026-08-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0035_alter_settings_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="dashboard_cards",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Select which cards to show on the dashboard, in order.",
                null=True,
                verbose_name="Dashboard cards",
            ),
        ),
    ]
